language: node_js
node_js:
- '0.12'
before_install:
- openssl aes-256-cbc -K $encrypted_25e5094d13b6_key -iv $encrypted_25e5094d13b6_iv
  -in id_rsa_github_pages.enc -out .travis/id_rsa_github_pages -d
after_success:
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - ./deploy
