language: node_js
node_js:
- '0.12'
# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - openssl aes-256-cbc -K $encrypted_25e5094d13b6_key -iv $encrypted_25e5094d13b6_iv
    -in .travis/deploy_key.enc -out .travis/deploy_key -d
install:
  - npm install
script:
  # - gulp lint
after_success:
  # - chmod 600 .travis/deploy_key # this key should have push access
  # - ssh-add .travis/deploy_key
  # - ./deploy.sh
