baseurl = "https://ataylor.io/"
languageCode = "en-us"
title = "Aaron Taylor"
description = "My personal site"
disqusShortname = "kujengatech"

# for github pages: https://gohugo.io/tutorials/github-pages-blog/
canonifyurls = true

[params]
	twitter = "https://twitter.com/ataylor0123"
	github = "https://github.com/kujenga"
	linkedin = "https://linkedin.com/in/ataylor0123"
	instagram = "https://instagram.com/ataylor0123/"
	angellist = "https://angel.co/aaron-taylor-1"
