baseurl = "https://ataylor.io/"
languageCode = "en-us"
title = "Aaron Taylor"
description = "My personal site"
disqusShortname = "kujengatech"
googleAnalytics = "UA-56787812-1"

[params]
	twitter = "https://twitter.com/ataylor0123"
	github = "https://github.com/kujenga"
	linkedin = "https://linkedin.com/in/ataylor0123"
	instagram = "https://instagram.com/ataylor0123/"
	angellist = "https://angel.co/ataylor0123"
	keybase = "https://keybase.io/ataylor"
