# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.14-node

    steps:
      - checkout

      - run:
          name: Print environment information
          command: |
            set -x
            go version
            go env
            node --version
            npm --version

      - run:
          name: Install Go-based tooling
          working_directory: 'tools'
          command: ./install-tools
      - run:
          name: Install Go app dependencies
          working_directory: 'app'
          command: go install -v

      - run:
          name: Run Go tests
          working_directory: 'app'
          command: go test -v ./...

      - run:
          name: Install Node-based tooling
          command: npm install
      - run:
          name: Run NPM lints
          working_directory: 'app'
          command: npm run lint
