# CircleCI configuration file

version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

jobs:
  build:
    docker:
      - image: cimg/go:1.14-node

    steps:
      - checkout

      # Environment
      - run:
          name: Print environment information
          command: |
            set -x
            go version
            go env
            node --version
            npm --version

      # Install
      - restore_cache:
          keys:
            - v4-go-deps-{{ checksum "app/go.mod" }}-{{ checksum "tools/go.mod" }}
            - v4-go-deps-
      - run:
          name: Install Go-based tooling
          working_directory: 'tools'
          command: ./install-tools
      - run:
          name: Install Go app dependencies
          working_directory: 'app'
          command: go install -v
      - save_cache:
          key: v4-go-deps-{{ checksum "app/go.mod" }}-{{ checksum "tools/go.mod" }}
          paths:
            # Observed from `go env` output, above
            - ~/go
            - ~/.cache

      # Go tests
      - run:
          name: Run Go tests
          working_directory: 'app'
          command: go test -v ./...

      # NPM tests
      - run:
          name: Install Node-based tooling
          command: npm install
      - run:
          name: Run NPM lints
          working_directory: 'app'
          command: npm run lint

      # Site build
      - run:
          name: Build site
          command: npm run build
      - store_artifacts:
          path: app/public
      - persist_to_workspace:
          root: .
          paths:
            - app/public

  deploy:
    executor: gcp-cli/google
    steps:
      # Uses pre-defined environment variables:
      # https://circleci.com/developer/orbs/orb/circleci/gcp-cli#commands-initialize
      # The service account was provisioned according to the instructions here,
      # with the exception of scoping the iam.serviceAccountUser role to the
      # specific App Engine service account, and the compute.storageAdmin role
      # to the specific storage buckets, ref:
      # https://cloud.google.com/appengine/docs/standard/go/roles#recommended_role_for_application_deployment
      - gcp-cli/initialize
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to App Engine
          command: >
            gcloud app deploy app/app.yaml
            --quiet
            --no-promote
            --version "$(./scripts/version)"

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
