runtime: go112

handlers:
# Configure App Engine to serve any static assets.
- url: /css
  static_dir: public/css
- url: /img
  static_dir: public/img

# Use HTTPS for all requests.
- url: /.*
  secure: always
  script: auto
